server:
  port: 9411
spring:
  application:
    name: cloud-sleuth
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

