server:
  port: 8762
spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/