server:
  port: 8767
spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
    ribbonapi:
      path: /ribbonapi/**
      serviceId: service-ribbon
    feignapi:
      path: /feignapi/**
      serviceId: service-feign
    zuul.prefix: v1
