server:
  port: 8767
spring:
  application:
    name: service-turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

#turbine熔断器监控配置
turbine:
  aggregator:
    cluster-config: default
  app-config: service-ribbon,service-feign
  cluster-name-expression: new String("default")